api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('projects/all', views.APIProjectsList.as_view(), name='api'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('django/admin/', admin.site.urls),
    path('django/', views.home, name='home'),
    path('django/blog/', include('blog.urls')),
    path('django/portfolio/', include('portfolio.urls'), name='portfolio'),
    path('django/contact/', views.contact, name='contact'),
    path('django/api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:project_id>/', views.detailProject, name='detailProject'),
]

api/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    dateBlog = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models
import datetime

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=700)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)
    dateProject = models.DateField(default=datetime.date.today)
    youtubeResourceID = models.CharField(blank=True,max_length=500)
    imageResource = models.ImageField(blank=True,upload_to='portfolio/images/')

    def __str__(self):
        return self.title

api/views.py
from rest_framework import generics, permissions
from .serializers import ProjectSerializer
from portfolio.models import Project

class APIProjectsList(generics.ListAPIView):
    serializer_class = ProjectSerializer

    def get_queryset(self):
        return Project.objects.filter(dateProject__isnull=False).order_by('-dateProject')

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def all_blogs(request):
    blogs = Blog.objects.order_by('-dateBlog')[:5]

    return render(request, 'blog/all_blogs.html', {'blogs': blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)

    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project
from blog.models import Blog
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404


def home(request):

    projects = Project.objects.order_by('-dateProject')
    blogs = Blog.objects.order_by('-dateBlog')[:3]
    
    paginator = Paginator(projects, 3)
        
    numProjects = 0
    page = request.GET.get('page')

    project = paginator.get_page(page)

    numProjects = len(project)

    return render(request, 'portfolio/home.html', {'projects': project,'blogs': blogs,'numProjects': numProjects})

def detailProject(request, project_id):
    project = get_object_or_404(Project, pk=project_id)

    return render(request, 'portfolio/detail.html', {'project': project})


def contact(request):
    return render(request, 'portfolio/contact.html')

def emmaGift(request):
    return render(request, 'portfolio/emma.html')

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}
{% block content %}

<div style="margin-left:1rem">
    <div style="padding-bottom:3rem">
        <h1>Blog</h1>
        <h3>Emmanuel has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h2>
    </div>

    {% for blog in blogs %}
        <div class="boxBlog" style="margin-bottom:3rem">
            <a href="{% url 'blog:detail' blog.id %}" style="text-decoration:none;"><h3 style="color:black; font-weight:bold;">{{ blog.title }}</h3></a>
            <h5 style="color:black">{{ blog.dateBlog|date:'M d Y'|upper }}</h5>
            <p>{{ blog.description|striptags|truncatechars:100 }}<p>
        </div>
    {% endfor %}
</div>
    
{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}

<div>
    <div class="caja-titulo-fecha">
        <h1>{{ blog.title }}</h1>
        <h5>{{ blog.dateBlog|date:'F jS Y' }}</h2>
    </div>
</div>
<div class="desc">
    <p style="text-align: justify;"> {{ blog.description|safe }} </p>
</div>

{% endblock %}

portfolio/templates/portfolio/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script>
      $(document).ready(function () {
      $("#all").fadeIn(2000);
      });
    </script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@100;300&display=swap" rel="stylesheet">     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Emmanuel Solorzano</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">
    <link rel="icon" type="image/png" href="{% static 'portfolio/E.png' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <img src="{% static 'portfolio/E.png' %}" class="littlePic">
          <a class="navbar-brand" href="{% url 'home' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
            
            
            <ul class="navbar-nav mb-2 mb-lg-0 derecha">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'api' %}">API</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% static 'portfolio/CV.pdf' %}">Resume</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="https://www.linkedin.com/in/emmanuel-solorzano/">LinkedIn</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'contact' %}">Contact</a>
              </li>
            </ul>


              <a href="{% url 'blog:all_blogs' %}"><button class="btn btn-primary" type="submit">Blog</button></a>
          </div>
        </div>
    </nav>

    <div class="wrapper"  id="all" style="display:none;">
      {% block content %}{% endblock %}
    </div>
    
    <footer class="footerBox">
      <div>
        <h3 class="footerText">Thank you for visiting my website!</h3>
      </div>
    </footer>
  
  </body>
</html>

portfolio/templates/portfolio/contact.html
{% extends 'portfolio/base.html' %}
{% block content %}

<!--Section: Contact v.2-->
<section class="mb-4" style="margin:1rem;">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact me</h2>

    <div class="row">

        <!--Grid column-->
        <div class="col-md-9 mb-md-0 mb-5" style="padding-right:0">
            <form id="contact-form" name="contact-form" action="mail.php" method="POST">

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6" style="margin-bottom:1rem">
                        <div class="md-form mb-0">
                            <input type="text" id="name" name="name" class="form-control">
                            <label for="name" class="">Your name</label>
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="email" name="email" class="form-control">
                            <label for="email" class="">Your email</label>
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12" style="margin-bottom:1rem">
                        <div class="md-form mb-0">
                            <input type="text" id="subject" name="subject" class="form-control">
                            <label for="subject" class="">Subject</label>
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                            <label for="message">Your message</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <div class="text-center text-md-left">
                <a style="border:solid 0.2rem; border-color:white;" class="btn btn-primary" onclick="document.getElementById('contact-form').submit();">Send</a>
            </div>
            <div class="status"></div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center" style="padding-left:0">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                    <p>Tepic, Nayarit</p>
                </li>

                <li><i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>+52 311 132 1467</p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                    <p>emahumsol@hotmail.com</p>
                </li>
            </ul>
        </div>
        <!--Grid column-->

    </div>

</section>
<!--Section: Contact v.2-->

{% endblock %}

portfolio/templates/portfolio/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}

<div>
    <div class="caja-titulo-fecha">
        <h1>{{ project.title }}</h1>
        <h5>{{ project.dateProject|date:'F jS Y' }}</h2>
    </div>
</div>
<div class="desc">
    <p style="text-align: justify;"> {{ project.description }} </p>
</div>
<div class="mediavid">
    {% if project.youtubeResourceID %}
    <div style="padding-bottom: 2rem">
        <iframe class="video" src="https://www.youtube.com/embed/{{ project.youtubeResourceID }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </div>
    {% endif %}
    {% if project.imageResource %}
    <div>
        <img src="{{ project.imageResource.url }}" width="300" height="200">
    </div>
    {% endif %}
</div>
{% endblock %}

portfolio/templates/portfolio/emma.html
{% extends 'portfolio/base.html' %}
{% block content %}

    <h1>Feliz cumpleaños amor</h1>
    <p>
        Quiero darte mi bendición en tu día para que todos tus días sean largos 
        y prósperos. Gracias por estar siempre en mi vida y por ser la luz
        que me ilumina y me acompaña. Cómo siempre te lo digo, eres luz. Te amo.
    </p>

    <p>
        Fue difícil saber qué regalarte, así que quise darte algo que pudiera serte
        útil, porque creo que es lo primero que piensas cada que tú vas a darme algo.
        Cuando te vayas a tu concierto de Taylor es probable que vaya a hacer frío,
        así que quise darte algo para que te vayas tapadita. No sé mucho de Taylor
        así que Marissa me ayudó a escoger la hoodie más bonita.
    </p>
    {% load static %}
    <img src="{% static 'portfolio/hoodie.jpg' %}" style="justify-content: center; height: 22rem; width: 100%;">

    <p>
        Según la página llega el día 26 de Abril, me hubiera encantado dártela hoy pero
        no quería darle una que no fuera oficial porque usted solo se merece lo mejor.
    </p>
    <img src="{% static 'portfolio/pago1.jpg' %}" style="justify-content: center; height: 25rem; width: 100%;">
    <img src="{% static 'portfolio/pago2.jpg' %}" style="justify-content: center; height: 20rem; width: 100%;">

    <p>
        Para rastrear el pedido has click en el número de guía:
    </p>
    <a href="https://www.redpack.com.mx/es/rastreo/?guias=083154990"><p>083154990</p></a>

{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}

<h1>Emmanuel Solorzano's Portfolio</h1>

<div class="intro">
    <h2>Welcome to my portfolio</h2>
    <p>A brief summary of my professional life</p>
</div>

<div class="container cards">
    <h3 class="izq">Recent Projects:</h3>

    <!-- Controls -->
    <div class="d-flex justify-content-center mb-4" style="display: flex; justify-content: center; margin-top: 1.5rem;">
        {% if projects.has_previous %}
            <a class="carousel-control-prev position-relative" href="?page={{ projects.previous_page_number }}">
        {% endif %}
        <button class="carousel-control-prev position-relative" type="button">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
        </button>
        {% if projects.has_previous %}
            </a>
        {% endif %}
            <div class="separation">
            </div>
        {% if projects.has_next %}
            <a class="carousel-control-next position-relative" href="?page={{ projects.next_page_number }}">
        {% endif %}
        <button class="carousel-control-next position-relative" type="button">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
        </button>
        {% if projects.has_next %}
        </a>
        {% endif %}
    </div>


    <div class="row align-items-start padding-bottom" style="color: black;">
        {% for project in projects %}
            <div class="col">
                <div class="card shadow-sm">
                    {% load static %}
                    {% if project.url %}
                        <a href="{{ project.url }}">
                    {% endif %}
                    <img src="{{ project.image.url }}" class="bd-placeholder-img card-img-top" width="100%" height="225">
                    {% if project.url %}
                        </a>
                    {% endif %}
                    <div class="card-body">
                        <h4 style="color:black; font-weight:bold;">{{ project.title }}</h4>
                        <p class="card-text">{{ project.description|striptags|truncatechars:40 }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'portfolio:detailProject' project.id %}" class="btn btn-primary" style="text-align:center;">See project</a>
                            <small class="text-muted">{{ project.dateProject|date:'M d Y'|upper }}</small>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if numProjects == 1 %}
                <div class="col" style="visibility:hidden;">
                    <div class="card shadow-sm">
                        <img src="" class="bd-placeholder-img card-img-top" width="100%" height="225">
                        <div class="card-body">
                            <h4 style="color:black; font-weight:bold;"></h4>
                            <p class="card-text"></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="#" class="btn btn-primary" style="text-align:center;"></a>
                                <small class="text-muted"></small>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col" style="visibility:hidden;">
                    <div class="card shadow-sm">
                        <img src="" class="bd-placeholder-img card-img-top" width="100%" height="225">
                        <div class="card-body">
                            <h4 style="color:black; font-weight:bold;"></h4>
                            <p class="card-text"></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="#" class="btn btn-primary" style="text-align:center;"></a>
                                <small class="text-muted"></small>
                            </div>
                        </div>
                    </div>
                </div>
        {% endif %}
        {% if numProjects == 2 %}
                <div class="col" style="visibility:hidden;">
                    <div class="card shadow-sm">
                        <img src="" class="bd-placeholder-img card-img-top" width="100%" height="225">
                        <div class="card-body">
                            <h4 style="color:black; font-weight:bold;"></h4>
                            <p class="card-text"></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="#" class="btn btn-primary" style="text-align:center;"></a>
                                <small class="text-muted"></small>
                            </div>
                        </div>
                    </div>
                </div>
        {% endif %}
    </div>
</div>

{{ projects.count }}

{% endblock %}